akademia_homepage:
    path:     /
    defaults: { _controller: AkademiaBundle:Default:index }
    methods:  [GET,POST]


akademia_registrar:
    path:     /registrar
    defaults: { _controller: AkademiaBundle:Default:registrar }
    methods:  [GET,POST]


akademia_getPost:
    path:     /post/get
    defaults: { _controller: AkademiaBundle:Default:post}
    methods:  [GET,POST]

akademia_registerFinal:
    path:     /register/final
    defaults: { _controller: AkademiaBundle:Default:registerFinal}
    methods:  [GET,POST]

akademia_generarPdfInscripcion:
    path:     /pdf/inscripcion/{id}
    defaults: { _controller: AkademiaBundle:Default:generarPdfInscripcion}
    methods:  [GET,POST]

akademia_generarPdfDeclaracionJurada:
    path:     /pdf/declaracion-jurada/{id}
    defaults: { _controller: AkademiaBundle:Default:generarPdfDeclaracionJurada}
    methods:  [GET,POST]

akademia_sendemail:
    path:     /sendemail
    defaults: { _controller: AkademiaBundle:Default:sendemail}
    methods:  [GET,POST]
